### ISSUE TITLE
Please sign this addon

### ISSUE THREAD

**Issue by andreicristianpetcu** [andymckay/sidebar-tabs#1]
Hi,

Please sign this addon. [I signed a clone](https://andreicristianpetcu.github.io/chrom2firefox/addons/unofficial_sidebar_tabs-1.0-an+fx.xpi) but it would be nice for other devs to click and see this API.

I used web-ext sign.

**Comment by andymckay** [comment]
When I feel its ready it will go on addons.mozilla.org, but right now I'm finding and fixing bugs in it.
