### ISSUE TITLE
UI: add-identities menus in inline; listen for container changes

### ISSUE THREAD

**Issue by yfdyh000** [andymckay/sidebar-tabs#10]
It will be suitable for a lot of containers, and save the interface space.
The concept: https://github.com/yfdyh000/sidebar-tabs/commit/1d00a4d538a28894c7b30e78838d5183cdf20cd6

It should be overflowed to multiple lines, or provide .../more button.

**Comment by andymckay** [comment]
Listening for container changes requires https://bugzilla.mozilla.org/show_bug.cgi?id=1344519 I believe.

**Comment by andymckay** [comment]
This is now unmaintained, let's use https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/ instead.
