### ISSUE TITLE
Too easy to click buttons accidentally

### ISSUE THREAD

**Issue by andymckay** [andymckay/sidebar-tabs#15]
Its too easy to click new window or pin or whatever. I think we should probably just have close and the rest of the choices hidden away in a context menu or sub HTML menu.

**Comment by ncalexan** [comment]
I wonder about expanding out the non-close buttons on hover or something like that, to maintain the "inline UI" but tuck it away when not wanted.

**Comment by andymckay** [comment]
That probably makes sense.

To be honest at this point as soon as https://github.com/eoger/tabcenter-redux lands on AMO, I'm probably just going to close this repo down though, its much nicer :)

**Comment by Keith94** [comment]
@andymckay It's on AMO now btw: https://addons.mozilla.org/firefox/addon/tab-center-redux/

**Comment by andymckay** [comment]
Sweet, I'm gonna totally give up on this one then I think. If you want to use it, fork away :)

**Comment by andymckay** [comment]
This is now unmaintained, let's use https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/ instead.
