### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Croydon** [andymckay/sidebar-tabs#16]
Can I assume this repository's code to be MPLv2 licensed?

I might want to take over some parts into my own vertical tabs solution.

**Comment by Croydon** [comment]
@andymckay Ping?

**Comment by andymckay** [comment]
Sure, will add a listen.

**Comment by andymckay** [comment]
Aargh... license and it will be MPLv2.

**Comment by Croydon** [comment]
Thanks :)

**Comment by andymckay** [comment]
Actually https://github.com/andymckay/sidebar-tabs/blob/master/LICENSE.md was added a while back.
