### ISSUE TITLE
Middle-clicking a tab should close it

### ISSUE THREAD

**Issue by Screwtapello** [andymckay/sidebar-tabs#17]
In the normal tab UI, middle-clicking a blank part of the tab-strip opens a new tab, while middle-clicking an open tab closes it.

Currently in Sidebar Tabs 1.10, middle-clicking a blank part of the tab-strip opens the URL from the clipboard in the active tab, and middle-clicking an open tab opens a new tab.

I realise that this might not be implementable due to the restrictions of WebExtensions, but I thought I'd mention it.

**Comment by andymckay** [comment]
This is now unmaintained, let's use https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/ instead.
