### ISSUE TITLE
Add close-all-below, close-all-above, close-all-but context menu items

### ISSUE THREAD

**Issue by ncalexan** [andymckay/sidebar-tabs#18]
The built in tab bar and Tab Center both have "Close other tabs" and "Close tabs to the Right".  I use that functionality a lot, to "pop the stack" of my browsing.  This ticket tracks implementing something similar in Sidebar Tabs, expecting that at some point we'll be able to hide the real tab bar and therefore not be able to access that functionality as a replacement.

My first read is that Web Extensions have an impoverished contextmenu API to work with to implement features like this, since the tab links aren't differentiated from other web content links and therefore can't get "Sidebar Tabs" specific behaviour.  Would like to be proven wrong here!

**Comment by andymckay** [comment]
Check out https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/, its got some nifty context menu choices.
