### ISSUE TITLE
Add-on Manager favicon can't be loaded

### ISSUE THREAD

**Issue by yfdyh000** [andymckay/sidebar-tabs#9]
![Screenshot](https://cloud.githubusercontent.com/assets/1769875/23703471/1482e89e-043b-11e7-9d87-0b86766f1ac4.png)
`chrome://mozapps/skin/extensions/extensionGeneric-16.png`

**Comment by andymckay** [comment]
Yeah, not sure what to do there, perhaps we should just catch an error on loading the icon?

**Comment by andymckay** [comment]
Wondering if this icon would be available in the moz-anno icon cache, something that we should use. But for the moment, its probably a good thing to not show an icon if the image fails to load.

**Comment by andymckay** [comment]
This is now unmaintained, let's use https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/ instead.
